registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
    - 443:443
  environment:
    REGISTRY_HTTP_HOST: ${HTTP_HOST}
    REGISTRY_HTTP_SECRET: ${HTTP_SECRET}
    REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE: ${LETSENCRYPT_CACHEFILE}
    REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - "${REGISTRY_DIR}:/var/lib/registry"
    - "${AUTH_DIR}:/auth"
    - "${LETSENCRYPT_CACHEFILE_LOCAL}:${LETSENCRYPT_CACHEFILE}"
